### PR TITLE
ko: webgl 3d perspective

### PR DESCRIPTION
**Pull request by TroyTae**
Before merge, can you check this please?
-> https://twitter.com/tjy970721/status/1355075462762909697

First, I try to send a direct message, but DM is blocked.

So I leave my question as a tweet 😓

### CODE REVIEW

**Comment by greggman** [comment]
Why not just leave a message here?

There's nothing wrong with the sentence AFAICT. It's a little awkward but it's correct.

**Comment by TroyTae** [comment]
I was still translating when I send that tweet.
And I thought this question is too small to leave as an issue 😓 
Anyway if you prefer to leave a message in PR, I'll do like that!
Please merge this :)

**Comment by TroyTae** [comment]
@greggman 
Do you have any other communication channels?
I can leave a question in the PR and revise it later, but sometimes the context changes entirely.
And if I can get quick feedback, it'll save time to understand your intentions.

**Comment by TroyTae** [comment]
@greggman 
 Apart from the comment above, how about add this image that used in your stackoverflow answer?
image

I thought about why I was hard to translate at here:
image

I think the reason is explanations of `zNear`, `FOV`, etc are written below the diagram.
That's why I compared with above `perspective` function several times and I asked a question in twitter.

So how about add that image or add some text in diagram??

**Comment by greggman** [comment]
Sorry I don't have a quick answer.

I don't mind adding that diagram or making a new one. But at the moment I don't have a good idea for how to explain the matrix. My personal opinion is that you don't need to know *why* the matrix works, you just need to know that it works. I know not everyone agrees with that POV. 

If you want to know why it works you should "apply the math" by walking through it like we didn from the [2d article](https://webglfundamentals.org/webgl/lessons/webgl-2d-matrices.html). Walking down

```
   var f = Math.tan(Math.PI * 0.5 - 0.5 * fieldOfViewInRadians);
   var rangeInv = 1.0 / (near - far);
   return [
      f / aspect, 0, 0, 0,
      0, f, 0, 0,
      0, 0, (near + far) * rangeInv, -1,
      0, 0, near * far * rangeInv * 2, 0
    ];
```

The first column scales X by f / aspect. 
The second column scales y by f. 
The 4th column outputs Z * -1 or -Z. 
The 3rd column is the only hard one but rather than work it out we can test it. It only affects Z and we stated it scales Z so -zNear = -1 and -zFar = 1 so

```
near = 1
far = 101
invRange = 1.0 / (near - far) = 1.0 / (1 - 101) = 1.0 / -100 = -0.01

Z * (near + far) * rangeInv = Z * (1 + 101) * -0.01 = Z * 102 * -0.01 = Z * -1.02

W * (near * far) * rangeInv * 2 = W * (1 * 101) * -0.01 * 2 = W * -2.02
```

So we just have `zResult = Z * -1.02 + W * -2.02`

```
Z = -near, W = 1 (always)
zResultNear = -1 * -1.02 + -2.02
zResultNear = -1

Z = -far
zResultFar = -101 * -1.02 + -2.02
ZResultFar = 101
```

So now we divide by the W output from the matrix which is -Z

```
clipSpaceZ = zResultNear / wResult = -1 / 1 = -1
clipSpaceW = zResultFar / wResult = 101 / 101 = 1
```

So yes, values form -zNear to -zFar get mapped to -1 to +1

Yes, I get that I just walked through that but how to walk through it is spelled out in [the 2d article](https://webglfundamentals.org/webgl/lessons/webgl-2d-matrices.html)

In any case, let me think about it.

**Comment by TroyTae** [comment]
@greggman 
Perhaps my opinion was misrepresented 😅 
I agree that people don't need to understand the matrix, maybe we can explain but it'll be too long.
I'm just worried order of paragraphs.

The term `zNear` first appears after the perspective function.
image

But the description is below the diagram.
image

I think some people can look above for finding definition of  `zNear` like me.
Maybe I was just a fool... Anyway this is my opinion :)

**Comment by greggman** [comment]
I see. I definitely agree consistent naming would be good.

which do you prefer?  `near` and `far` or `zNear` and `zFar`?

**Comment by TroyTae** [comment]
@greggman 
I think `zNear` and `zFar` are better!

**Pull request merged**
