### PR TITLE
ko: update webgl-shaders-and-glsl.md

### PR DESCRIPTION
**Pull request by TroyTae**
One small thing:
image
If I translate `header`, hash anchor(`#putting-it-all-together`) isn't worked.
Is there any solution about this?
Or do I have to leave it as it was??

### CODE REVIEW

**Comment by greggman** [comment]
Where is the hash referenced?

**Comment by TroyTae** [comment]
@greggman 
For example, these kind of things:
image

**Comment by greggman** [comment]
Yes but since the are referencing Korean you can change those to the matching Korean id, right?

Some file

```
## 기초
```

Some other file

```
[bla bla](somefile.html#기초)
```

etc...

**Comment by TroyTae** [comment]
Ah I see, I thought only ascii code can use as hash.
I'll reflect it!

**Comment by greggman** [comment]
just fyi, you can also use anchors like this

```
<a id="foo">
# some topic
```

```
[some text](#foo)
```

**Pull request merged**
