### PR TITLE
ko: webgl 2d vs 3d library

### PR DESCRIPTION
**Pull request by TroyTae**
Before merge, I wanna ask a question.
This part(`where I'm coming from`) of this sentence(`I hope you at least understand where I'm coming from when I say WebGL is not a 3D library.`) means really where you're coming from?
Or it means where the WebGL is coming from? (= WebGL origin)

Please don't merge immediately, I'll reflect above question :)

### CODE REVIEW

**Comment by greggman** [comment]
It's an idiom. It means "I hope you can understand my point of view / opinion"

https://idioms.thefreedictionary.com/where+I+am+coming+from#:~:text=One's%20motivation%20or%20reason%20for,t%20let%20you%20do%20that.

**Comment by TroyTae** [comment]
Ah I see, I'm sorry, my english skill is weak 😅 
I'll reflect it right now

**Comment by greggman** [comment]
No worries. My Korean skills are zero 😅

**Comment by TroyTae** [comment]
I've committed it all~!

**Pull request merged**
