### PR TITLE
fix: overflow issue in mobile

### PR DESCRIPTION
**Pull request by TroyTae**
There are some horizontal overflow issue in mobile(iPhone SE2).

### Fixing List

**overflow-x**
 - 2d-matrices
 - 3d-camera
 - drawing-multiple-things
 - data-textures
 - shadertoy
 - cross-platform-issues
 - readpixels

**word-break**
 - 3d-lighting-directional
 - attributes

### Some Captures

2d-matrices
3d-camera

### CODE REVIEW

**Comment by greggman** [comment]
Thanks for pointing this out. I ended up fixing it differently

https://github.com/gfxfundamentals/webgl-fundamentals/commit/6a043abaa8c664ab01144623676503cb9e323337

https://github.com/gfxfundamentals/webgl-fundamentals/commit/1d2fd9df52260923a7649bac8a32b316d35677b0

https://github.com/gfxfundamentals/webgl-fundamentals/commit/f56336b61037c487d4fcbcdb5c2c96da1c61f872

**Comment by TroyTae** [comment]
Thank you!
Can you check one more last time?
The others are cool :)

https://webglfundamentals.org/webgl/lessons/webgl-image-processing-continued.html
image

**Comment by greggman** [comment]
https://github.com/gfxfundamentals/webgl-fundamentals/commit/131d07d95578ee4eb48057744b7c92131f807178

**Comment by TroyTae** [comment]
👍

**Pull request closed without merging**
